name: JavaScript CI

on:
  push:
    branches: [ Trunk ]
  pull_request:
    branches: [ Trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint --if-present
    - run: npm test

    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        node-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest scapy colorama 
    - name: Run pytest
      run: pytest
